### ISSUE TITLE
Maps do not show in the first tab

### ISSUE THREAD

**Issue by srikanthguhan** [JerryTsien/vWorldEcon#1]
![capture](https://cloud.githubusercontent.com/assets/10030043/9432961/df61e244-4a48-11e5-8dfc-97c787e3d359.PNG)

**Comment by JerryTsien** [comment]
![americas](https://cloud.githubusercontent.com/assets/11316924/9435124/f2f5b058-4a3c-11e5-9f12-6bb73028e68b.png)
It works in my browser, however. I think the probable cause is server utilization restrictions on shinyapps, which limit CPU intensive functions calls. Right now the work-around is to wait until the webpage is fully loaded before making the next selection. And it also helps if you use arrow keys to select the desired year. Sorry about the inconvenience.

**Comment by srikanthguhan** [comment]
Can see the maps now.
